version: '3.8'

services:
  app:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
